// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wiwi.ScheduleCenter.Core.Infrastructure;

#nullable disable

namespace Wiwi.ScheduleCenter.Api.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20230322005729_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wiwi.ScheduleCenter.Core.Domain.ScheduleModel", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("schedule_id")
                        .HasComment("主键");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<string>("Creater")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("creater")
                        .HasComment("创建人");

                    b.Property<string>("CreaterId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("create_id")
                        .HasComment("创建人Id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("LastModifier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("last_modifier")
                        .HasComment("最后修改人");

                    b.Property<string>("LastModifierId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("last_modifier_id")
                        .HasComment("最后修改人Id");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modify_time")
                        .HasComment("最后修改时间");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_run_time");

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_run_time");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("request_url");

                    b.Property<string>("ShcheduleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("schedule_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.ToTable("ScheduleModel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
